=== blackhatgeek/netsimul/NetTrafficSimulator/NetTrafficSimulator/model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1"
targetNamespace="http://ms.mff.cuni.cz/~mansuroa/netsimul/model/v0" xmlns:ns="http://ms.mff.cuni.cz/~mansuroa/netsimul/model/v0">
	<xs:element name="simulation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="model" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodes" type="ns:tNode" minOccurs="0" maxOccurs="1"/>
							<xs:element name="links" type="ns:tLink" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="events" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:choice>
							<xs:element name="event" type="ns:tEvent" minOccurs="1" maxOccurs="unbounded"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="time_run" use="required" type="xs:nonNegativeInteger"/>
			<xs:attribute name="max_hop" use="optional" default="30" type="xs:positiveInteger"/>
			<xs:attribute name="version" use="required" type="xs:decimal" fixed="0.03"/>
		</xs:complexType>
		<xs:unique name="NodeName">
			<xs:selector xpath="child::network/nodes" />
			<xs:field xpath="./@name" />
		</xs:unique>
		<xs:unique name="LinkName">
			<xs:selector xpath="network/links/link" />
			<xs:field xpath="./@name" />
		</xs:unique>
		<xs:keyref name="LinkNode1" refer="ns:NodeName">
			<xs:selector xpath="network/links/link" />
			<xs:field xpath="./@node1" />
		</xs:keyref>
		<xs:keyref name="LinkNode2" refer="ns:NodeName">
			<xs:selector xpath="network/links/link" />
			<xs:field xpath="./@node2" />
		</xs:keyref>
		<xs:keyref name="EventWho" refer="ns:NodeName">
			<xs:selector xpath="events/event" />
			<xs:field xpath="./@who" />
		</xs:keyref>
		<xs:keyref name="EventWhere" refer="ns:NodeName">
			<xs:selector xpath="events/event" />
			<xs:field xpath="./@where" />
		</xs:keyref>
		<xs:keyref name="DefaultRoute" refer="ns:LinkName">
			<xs:selector xpath="network/nodes/network"/>
			<xs:field xpath="./@default"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="tNode">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="server" type="ns:tEndpoint" />
			<xs:element name="end">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ns:tEndpoint">
							<xs:attribute name="mps" type="xs:nonNegativeInteger" use="optional" />
							<xs:attribute name="randomTalk" type="xs:boolean" use="optional" default="false" />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="network" type="ns:tNetwork" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="tEndpoint">
		<xs:attribute name="name" type="xs:token" use="required" />
		<xs:attribute name="address" type="xs:nonNegativeInteger" use="required" />
	</xs:complexType>
	<xs:complexType name="tNetwork">
		<xs:attribute name="name" type="xs:token" use="required" />
		<xs:attribute name="default" type="xs:token" use="required" />
	</xs:complexType>
	<xs:complexType name="tLink">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="link">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="node1" type="xs:token" use="required" />
					<xs:attribute name="node2" type="xs:token" use="required" />
					<xs:attribute name="capacity" type="xs:nonNegativeInteger" use="required" />
					<xs:attribute name="toggle_probability" type="xs:decimal" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="tEvent">
		<xs:attribute name="who" type="xs:token" use="required" />
		<xs:attribute name="when" type="xs:nonNegativeInteger" use="required" />
		<xs:attribute name="where" type="xs:token" use="required" />
		<xs:attribute name="size" type="xs:decimal" use="optional" default="1" />
	</xs:complexType>
</xs:schema>

=== blackhatgeek/netsimul/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation time_run="5" version="0.03" xmlns="http://ms.mff.cuni.cz/~mansuroa/netsimul/model/v0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ms.mff.cuni.cz/~mansuroa/netsimul/model/v0 model.xsd">
	<network>
		<nodes>
			<server name="s1" address="1"/>
			<end name="e1" address="2" mps="5" randomTalk="true" />
			<network name="n1"/>
		</nodes>
		<links>
			<link name="l1" node1="s1" node2="n1" capacity="5" toggle_probability="0.0" />
			<link name="l2" node1="e1" node2="n1" capacity="10" toggle_probability="0.0" />
		</links>
	</network>
</simulation>
